import React, { useState, useEffect, useRef } from "react";

/* ─────────────────────────────────────────────
   DATA
───────────────────────────────────────────── */
const SECTIONS = [
  {
    id: "overview",
    number: "01",
    title: "Overview",
    subtitle: "Our Commitment to Your Privacy",
    content: [
      {
        type: "text",
        value:
          'WebXGuard ("we," "our," or "us") operates as a web application security platform providing vulnerability scanning, compliance tracking, and threat intelligence services. This Privacy Policy describes how we collect, process, store, and protect personal information when you use our platform, visit our website, or interact with our services.',
      },
      {
        type: "text",
        value:
          "By accessing or using WebXGuard, you agree to the collection and use of information in accordance with this policy. If you do not agree with the terms described here, please discontinue use of our services.",
      },
      {
        type: "highlight",
        value:
          "This policy applies to all users of the WebXGuard platform, including free-tier users, paid subscribers, and enterprise clients. It does not apply to third-party services or websites linked from our platform.",
      },
    ],
  },
  {
    id: "collection",
    number: "02",
    title: "Information We Collect",
    subtitle: "Transparent Data Collection",
    content: [
      {
        type: "text",
        value:
          "We collect several types of information in connection with your use of our services, including information you provide directly, data generated automatically through your use of the platform, and information we receive from third-party sources.",
      },
      { type: "subheading", value: "Information You Provide" },
      {
        type: "list",
        items: [
          "Account registration details: name, email address, company name, job title",
          "Billing and payment information (processed securely via third-party processors)",
          "Target website URLs and domains submitted for vulnerability scanning",
          "Support requests, feedback, and communications with our team",
          "Survey responses and product feedback",
        ],
      },
      { type: "subheading", value: "Automatically Collected Data" },
      {
        type: "list",
        items: [
          "IP addresses, browser type, operating system, and device identifiers",
          "Usage logs including pages visited, features accessed, and scan history",
          "Performance metrics and error reports for platform improvement",
          "Session duration, click paths, and interaction patterns",
        ],
      },
      {
        type: "grid",
        cards: [
          {
            label: "Scan Data",
            text: "Technical scan results and vulnerability reports generated by our engine when analyzing submitted URLs.",
          },
          {
            label: "API Usage",
            text: "Request logs, API keys, endpoint access patterns, and integration metadata for developer accounts.",
          },
        ],
      },
    ],
  },
  {
    id: "use",
    number: "03",
    title: "How We Use Your Data",
    subtitle: "Purposeful & Lawful Processing",
    content: [
      {
        type: "text",
        value:
          "We use the information we collect for the following purposes, always ensuring that processing is lawful, fair, and transparent.",
      },
      {
        type: "list",
        items: [
          "Providing, maintaining, and improving our vulnerability scanning and security services",
          "Processing transactions, managing subscriptions, and sending billing-related communications",
          "Personalising your experience and delivering relevant security insights and alerts",
          "Communicating product updates, security advisories, and service announcements",
          "Detecting and preventing fraudulent activity, abuse, and security breaches",
          "Conducting research and analytics to understand platform usage and improve features",
          "Complying with legal obligations and regulatory requirements",
          "Enforcing our Terms of Service and other applicable agreements",
        ],
      },
      {
        type: "highlight",
        value:
          "We do not sell your personal information to third parties for their own marketing purposes. Data processed through our scanning engine is used exclusively to generate your security reports.",
      },
    ],
  },
  {
    id: "sharing",
    number: "04",
    title: "Data Sharing & Disclosure",
    subtitle: "Limited & Controlled Sharing",
    content: [
      {
        type: "text",
        value:
          "We do not sell, trade, or rent your personal information. We may share your data only in the limited circumstances described below.",
      },
      { type: "subheading", value: "Service Providers" },
      {
        type: "text",
        value:
          "We engage trusted third-party vendors to assist in operating our platform, including cloud hosting providers, payment processors, and analytics services. These providers access only the data necessary to perform their functions and are contractually obligated to protect it.",
      },
      { type: "subheading", value: "Legal Requirements" },
      {
        type: "text",
        value:
          "We may disclose your information if required by applicable law, court order, or governmental authority, or when we believe in good faith that such disclosure is necessary to protect our rights or the safety of others.",
      },
      { type: "subheading", value: "Business Transfers" },
      {
        type: "text",
        value:
          "In the event of a merger, acquisition, or sale of company assets, user information may be transferred as part of that transaction. We will notify affected users of any such change in ownership or control.",
      },
      {
        type: "highlight",
        value:
          "We require all third parties receiving your data to maintain appropriate security measures and to use the data only for the specified purposes for which it was shared.",
      },
    ],
  },
  {
    id: "retention",
    number: "05",
    title: "Data Retention",
    subtitle: "Defined Retention Periods",
    content: [
      {
        type: "text",
        value:
          "We retain personal information for as long as necessary to fulfil the purposes for which it was collected, comply with our legal obligations, resolve disputes, and enforce our agreements.",
      },
      {
        type: "grid",
        cards: [
          {
            label: "Account Data",
            text: "Retained for the duration of your active account plus 90 days after a deletion request.",
          },
          {
            label: "Scan Reports",
            text: "Stored for up to 12 months on paid plans, 30 days on free-tier accounts.",
          },
          {
            label: "Billing Records",
            text: "Retained for 7 years in accordance with financial and tax regulations.",
          },
          {
            label: "Usage Logs",
            text: "Aggregated analytics data retained for up to 24 months for platform improvement.",
          },
        ],
      },
    ],
  },
  {
    id: "security",
    number: "06",
    title: "Security Measures",
    subtitle: "Enterprise-Grade Protection",
    content: [
      {
        type: "text",
        value:
          "We implement industry-standard technical and organisational security measures to protect your personal information against unauthorised access, alteration, disclosure, or destruction.",
      },
      {
        type: "list",
        items: [
          "AES-256 encryption for data at rest across all storage systems",
          "TLS 1.3 encryption for all data in transit between your browser and our servers",
          "Multi-factor authentication (MFA) available and recommended for all accounts",
          "Regular penetration testing and third-party security audits",
          "Role-based access controls limiting internal data access to authorised personnel only",
          "24/7 intrusion detection and real-time threat monitoring",
          "SOC 2 Type II compliance and regular security certifications",
        ],
      },
      {
        type: "text",
        value:
          "While we strive to use commercially acceptable means to protect your data, no method of transmission over the internet is 100% secure. In the event of a data breach, we will notify affected users in accordance with applicable legal requirements.",
      },
    ],
  },
  {
    id: "rights",
    number: "07",
    title: "Your Rights",
    subtitle: "Control Over Your Data",
    content: [
      {
        type: "text",
        value:
          "Depending on your jurisdiction, you may have specific rights regarding your personal information. We are committed to honouring these rights promptly and transparently.",
      },
      {
        type: "list",
        items: [
          "Right to access the personal data we hold about you",
          "Right to correct inaccurate or incomplete information",
          'Right to deletion ("right to be forgotten") subject to legal retention requirements',
          "Right to data portability in a structured, machine-readable format",
          "Right to object to or restrict certain types of processing",
          "Right to withdraw consent where processing is consent-based",
          "Right to lodge a complaint with your local data protection authority",
        ],
      },
      {
        type: "highlight",
        value:
          "To exercise any of these rights, contact our Data Protection Officer at privacy@webxguard.com. We will respond to verified requests within 30 days.",
      },
    ],
  },
  {
    id: "cookies",
    number: "08",
    title: "Cookies & Tracking",
    subtitle: "Cookie Usage & Your Preferences",
    content: [
      {
        type: "text",
        value:
          "We use cookies and similar tracking technologies to enhance your experience, understand usage patterns, and deliver relevant content. You can manage your cookie preferences through your browser settings or our cookie preference centre.",
      },
      {
        type: "list",
        items: [
          "Essential cookies required for core platform functionality and security",
          "Analytics cookies to understand how users interact with our platform",
          "Preference cookies to remember your settings and customisations",
          "Marketing cookies used only with your explicit consent",
        ],
      },
      {
        type: "text",
        value:
          "You may disable non-essential cookies at any time. Note that disabling certain cookies may affect platform functionality.",
      },
    ],
  },
  {
    id: "children",
    number: "09",
    title: "Children's Privacy",
    subtitle: "Protection of Minors",
    content: [
      {
        type: "text",
        value:
          "WebXGuard is intended for professional and business use only. Our services are not directed to individuals under the age of 16. We do not knowingly collect personal information from minors.",
      },
      {
        type: "text",
        value:
          "If we become aware that we have inadvertently collected personal information from a child under 16, we will take immediate steps to delete that information. If you believe a minor has provided us with personal data, please contact us immediately.",
      },
    ],
  },
  {
    id: "changes",
    number: "10",
    title: "Policy Changes",
    subtitle: "Staying Informed",
    content: [
      {
        type: "text",
        value:
          "We may update this Privacy Policy periodically to reflect changes in our practices, technology, legal requirements, or other factors. When we make material changes, we will notify you by email and by posting a prominent notice on our platform.",
      },
      {
        type: "text",
        value:
          "Your continued use of WebXGuard following the posting of a revised policy constitutes your acceptance of the changes. We encourage you to review this policy periodically to stay informed about how we protect your information.",
      },
    ],
  },
  {
    id: "contact",
    number: "11",
    title: "Contact Us",
    subtitle: "We're Here to Help",
    content: [
      {
        type: "text",
        value:
          "For questions, concerns, or requests related to this Privacy Policy or your personal data, please reach out to our Data Protection Officer through the channels below.",
      },
      {
        type: "contact",
        details: [
          { label: "Department", value: "Data Protection Officer" },
          { label: "Company", value: "WebXGuard Security Inc." },
          { label: "Privacy", value: "privacy@webxguard.com", isEmail: true },
          { label: "Support", value: "support@webxguard.com", isEmail: true },
          { label: "Response", value: "Within 30 business days" },
        ],
      },
    ],
  },
];

/* ─────────────────────────────────────────────
   BLOCK RENDERERS
───────────────────────────────────────────── */
function renderBlock(block, i) {
  switch (block.type) {
    case "text":
      return (
        <p key={i} className="mt-4 text-lg text-gray-300 leading-relaxed">
          {block.value}
        </p>
      );

    case "highlight":
      return (
        <div
          key={i}
          className="mt-6 border-l-2 border-emerald-500 bg-emerald-500/5 px-5 py-4 rounded-r-xl"
        >
          <p className="text-gray-300 leading-relaxed">{block.value}</p>
        </div>
      );

    case "subheading":
      return (
        <h3
          key={i}
          className="mt-8 mb-2 text-sm font-semibold uppercase tracking-widest text-emerald-400"
        >
          {block.value}
        </h3>
      );

    case "list":
      return (
        <ul key={i} className="mt-4 space-y-3">
          {block.items.map((item, j) => (
            <li
              key={j}
              className="flex items-start gap-3 text-gray-300 leading-relaxed"
            >
              <span className="mt-1.5 shrink-0 w-2 h-2 rounded-full bg-emerald-500/60" />
              {item}
            </li>
          ))}
        </ul>
      );

    case "grid":
      return (
        <div key={i} className="mt-6 grid grid-cols-1 sm:grid-cols-2 gap-4">
          {block.cards.map((card) => (
            <div
              key={card.label}
              className="bg-gray-800/50 border border-gray-700/60 rounded-2xl p-5 hover:border-emerald-500/30 transition-colors duration-300"
            >
              <p className="text-xs font-semibold uppercase tracking-widest text-emerald-400 mb-2">
                {card.label}
              </p>
              <p className="text-gray-300 text-sm leading-relaxed">
                {card.text}
              </p>
            </div>
          ))}
        </div>
      );

    case "contact":
      return (
        <div
          key={i}
          className="mt-6 bg-gray-800/50 border border-gray-700/60 rounded-2xl p-6 space-y-4"
        >
          {block.details.map(({ label, value, isEmail }) => (
            <div key={label} className="flex items-center gap-4">
              <span className="text-xs font-semibold uppercase tracking-widest text-gray-500 w-24 shrink-0">
                {label}
              </span>
              {isEmail ? (
                <a
                  href={`mailto:${value}`}
                  className="text-emerald-400 hover:text-emerald-300 transition-colors text-sm"
                >
                  {value}
                </a>
              ) : (
                <span className="text-gray-300 text-sm">{value}</span>
              )}
            </div>
          ))}
        </div>
      );

    default:
      return null;
  }
}

/* ─────────────────────────────────────────────
   TOC SIDEBAR
───────────────────────────────────────────── */
function TOC({ activeId }) {
  const scrollTo = (id) =>
    document
      .getElementById(id)
      ?.scrollIntoView({ behavior: "smooth", block: "start" });

  return (
    <aside className="hidden xl:block w-56 shrink-0 sticky top-28 self-start">
      <div className="sticky top-10">
        <p className="text-xs font-semibold uppercase tracking-widest text-emerald-400 mb-5">
          Contents
        </p>
        <nav className="space-y-1">
          {SECTIONS.map(({ id, number, title }) => (
            <button
              key={id}
              onClick={() => scrollTo(id)}
              className={`group w-full flex items-center gap-3 text-left px-3 py-2 rounded-lg text-xs border transition-all duration-200 ease-in-out ${
                activeId === id
                  ? "bg-emerald-500/10 text-emerald-400 border-emerald-400"
                  : "text-gray-500 border-transparent hover:text-gray-300 hover:bg-gray-800/50"
              }`}
            >
              <span
                className={`font-mono text-[10px] shrink-0 transition-colors ${
                  activeId === id
                    ? "text-emerald-500"
                    : "text-gray-600 group-hover:text-gray-400"
                }`}
              >
                {number}
              </span>
              {title}
            </button>
          ))}
        </nav>
      </div>
    </aside>
  );
}

/* ─────────────────────────────────────────────
   HERO  (matches FeatureHero style)
───────────────────────────────────────────── */
function PrivacyHero() {
  return (
    <section className="relative w-full overflow-hidden bg-gray-950 text-center py-28">
      {/* radial glow */}
      <div className="absolute inset-0 flex items-start justify-center pointer-events-none">
        <div className="w-[600px] h-[300px] bg-emerald-500/10 blur-[100px] rounded-full mt-8" />
      </div>

      {/* subtle grid */}
      <div
        className="absolute inset-0 pointer-events-none opacity-20"
        style={{
          backgroundImage:
            "linear-linear(rgba(16,185,129,0.15) 1px, transparent 1px), linear-linear(90deg, rgba(16,185,129,0.15) 1px, transparent 1px)",
          backgroundSize: "48px 48px",
        }}
      />

      <div className="relative z-10 max-w-3xl mx-auto px-6">
        <span className="inline-block text-xs font-medium uppercase tracking-widest text-emerald-400 border border-emerald-500/30 bg-emerald-500/5 rounded-full px-4 py-1.5 mb-8">
          Legal Documentation
        </span>

        <h1 className="text-4xl md:text-6xl font-extrabold text-gray-100 leading-tight mb-5">
          Privacy <span className="text-emerald-400">Policy</span>
        </h1>

        <p className="text-lg text-gray-400 leading-relaxed max-w-xl mx-auto">
          We are committed to protecting your personal data and being
          transparent about how we collect, use, and safeguard your information.
        </p>

        <div className="flex flex-wrap justify-center gap-3 mt-8">
          {[
            "Effective: Jan 1, 2025",
            "Updated: Mar 1, 2025",
            "Version 2.4",
          ].map((tag) => (
            <span
              key={tag}
              className="flex items-center gap-2 text-xs text-gray-400 bg-gray-800/60 border border-gray-700/60 rounded-full px-4 py-1.5"
            >
              <span className="w-1.5 h-1.5 rounded-full bg-emerald-500" />
              {tag}
            </span>
          ))}
        </div>
      </div>
    </section>
  );
}

/* ─────────────────────────────────────────────
   PAGE  (matches FeatureMain structure)
───────────────────────────────────────────── */
export default function PrivacyPolicy() {
  const [activeId, setActiveId] = useState("overview");
  const observerRef = useRef(null);

  useEffect(() => {
    observerRef.current = new IntersectionObserver(
      (entries) => {
        const visible = entries.find((e) => e.isIntersecting);
        if (visible) setActiveId(visible.target.id);
      },
      { rootMargin: "-40% 0px -50% 0px", threshold: 0.1 },
    );

    SECTIONS.forEach(({ id }) => {
      const el = document.getElementById(id);
      if (el) observerRef.current.observe(el);
    });

    return () => observerRef.current?.disconnect();
  }, []);

  return (
    <section className="relative w-full bg-linear-to-b from-gray-950 via-gray-900 to-gray-950">
      <PrivacyHero />

      {/* thin emerald divider, same as the shimmer lines in FeatureMain */}
      <div className="w-full h-px bg-linear-to-r from-transparent via-emerald-500/30 to-transparent" />

      <div className="max-w-7xl mx-auto px-4 md:px-12 py-20 flex gap-12">
        <TOC activeId={activeId} />

        <main className="flex-1 min-w-0 space-y-20 pr-4">
          {SECTIONS.map(({ id, number, title, subtitle, content }) => (
            <article key={id} id={id} className="scroll-mt-24">
              {/* header — mirrors the feature card header pattern */}
              <span className="text-emerald-400 text-sm font-medium">
                {subtitle}
              </span>
              <h2 className="mt-3 text-3xl md:text-4xl font-semibold text-gray-100 flex items-center gap-4">
                {title}
                <span className="text-sm font-mono text-gray-600">
                  {number}
                </span>
              </h2>

              {/* divider */}
              <div className="mt-5 mb-6 h-px w-full bg-linear-to-r from-emerald-500/20 via-gray-700 to-transparent" />

              {/* blocks */}
              <div>{content.map((block, i) => renderBlock(block, i))}</div>
            </article>
          ))}
        </main>
      </div>
    </section>
  );
}
