// src/pages/dashboard/PredictiveAnalysis.jsx
// Forecast + trend + at-risk pages — REAL DB DATA from posture_snapshots.

import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  TrendingUp,
  TrendingDown,
  Brain,
  Loader2,
  RefreshCw,
  AlertTriangle,
  Activity,
  Clock,
  Globe,
  Eye,
} from "lucide-react";
import {
  LineChart,
  Line,
  Area,
  AreaChart,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  Legend,
} from "recharts";
import { getPredictive } from "../../services/extras_api";

export default function PredictiveAnalysis() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const navigate = useNavigate();

  const load = async () => {
    setLoading(true);
    try {
      // No sessionId → backend returns latest posture for any monitored domain
      const d = await getPredictive();
      setData(d);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
  }, []);

  // ── Loading state ──────────────────────────────────────────────────────────
  if (loading) {
    return (
      <div className="min-h-screen flex justify-center items-center text-slate-400">
        <Loader2 className="animate-spin mr-2" size={20} />
        Running predictive model...
      </div>
    );
  }

  // ── Empty state ───────────────────────────────────────────────────────────
  if (!data) {
    return (
      <section className="min-h-screen text-white">
        <div className="max-w-6xl mx-auto mb-8">
          <div className="flex items-center gap-3 mb-1">
            <div className="w-9 h-9 rounded-xl bg-emerald-500/10 flex items-center justify-center">
              <Brain size={18} className="text-emerald-400" />
            </div>
            <h1 className="text-3xl font-bold text-white">
              Predictive Analysis
            </h1>
          </div>
          <p className="text-slate-400 text-sm ml-12">
            ML-driven forecasts powered by the posture engine
          </p>
        </div>

        <div className="max-w-6xl mx-auto">
          <div className="bg-[#111827] border border-slate-800 border-dashed rounded-2xl p-12 text-center">
            <Brain size={40} className="text-slate-700 mx-auto mb-3" />
            <p className="text-slate-400 font-medium">No predictive data yet</p>
            <p className="text-slate-600 text-sm mt-1 mb-5">
              Predictive analysis is generated by the continuous monitoring
              engine. Add a website to monitoring and wait for the first
              monitoring cycle to complete.
            </p>
            <div className="flex items-center justify-center gap-3">
              <button
                onClick={() => navigate("/dashboard/continuousmonitoring")}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl bg-emerald-500 text-slate-900 font-semibold text-sm hover:bg-emerald-400 transition cursor-pointer"
              >
                <Eye size={16} /> Open Continuous Monitoring
              </button>
              <button
                onClick={load}
                className="inline-flex items-center gap-2 px-5 py-2.5 rounded-xl border border-slate-700 text-slate-400 text-sm hover:text-white hover:border-slate-500 transition cursor-pointer"
              >
                <RefreshCw size={14} /> Refresh
              </button>
            </div>
          </div>
        </div>
      </section>
    );
  }

  // ── Normal render ─────────────────────────────────────────────────────────
  const { forecast, trend, at_risk, summary, domain } = data;
  const isIncreasing = summary?.direction === "increasing";

  return (
    <section className="min-h-screen text-white">
      {/* Header */}
      <div className="max-w-6xl mx-auto mb-8">
        <div className="flex items-center justify-between flex-wrap gap-4">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <div className="w-9 h-9 rounded-xl bg-emerald-500/10 flex items-center justify-center">
                <Brain size={18} className="text-emerald-400" />
              </div>
              <h1 className="text-3xl font-bold text-white">
                Predictive Analysis
              </h1>
            </div>
            <p className="text-slate-400 text-sm ml-12">
              {domain || "—"} • ML-driven forecasts and at-risk pages
            </p>
          </div>

          <button
            onClick={load}
            disabled={loading}
            className="flex items-center gap-2 px-4 py-2 rounded-xl border border-slate-700
              text-slate-400 text-sm hover:text-white hover:border-slate-500 transition cursor-pointer"
          >
            <RefreshCw size={14} className={loading ? "animate-spin" : ""} />
            Refresh
          </button>
        </div>
      </div>

      {/* Summary cards */}
      <div className="max-w-6xl mx-auto grid grid-cols-1 sm:grid-cols-3 gap-4 mb-6">
        <div className="bg-[#111827] border border-slate-800 rounded-xl p-5">
          <div className="flex items-center gap-2 text-slate-500 text-xs mb-2">
            {isIncreasing ? (
              <TrendingUp size={13} className="text-red-400" />
            ) : (
              <TrendingDown size={13} className="text-emerald-400" />
            )}
            Risk Trajectory
          </div>
          <p
            className={`text-2xl font-bold ${
              isIncreasing ? "text-red-400" : "text-emerald-400"
            }`}
          >
            {isIncreasing ? "+" : "-"}
            {summary?.delta_pct ?? 0}%
          </p>
          <p className="text-xs text-slate-600 mt-1">vs recent baseline</p>
        </div>

        <div className="bg-[#111827] border border-slate-800 rounded-xl p-5">
          <div className="flex items-center gap-2 text-slate-500 text-xs mb-2">
            <Activity size={13} className="text-emerald-400" />
            Model Confidence
          </div>
          <p className="text-2xl font-bold text-white">
            {Math.round((summary?.confidence ?? 0) * 100)}%
          </p>
          <p className="text-xs text-slate-600 mt-1">Prediction accuracy</p>
        </div>

        <div className="bg-[#111827] border border-slate-800 rounded-xl p-5">
          <div className="flex items-center gap-2 text-slate-500 text-xs mb-2">
            <Clock size={13} className="text-amber-400" />
            Next Review
          </div>
          <p className="text-2xl font-bold text-white">
            {summary?.next_review_in_days ?? "—"}{" "}
            <span className="text-base text-slate-500">days</span>
          </p>
          <p className="text-xs text-slate-600 mt-1">Recommended re-scan</p>
        </div>
      </div>

      {/* Forecast chart */}
      {forecast && forecast.length > 0 && (
        <div className="max-w-6xl mx-auto bg-[#111827] border border-slate-800 rounded-2xl p-6 mb-6">
          <div className="flex items-center justify-between mb-5">
            <div>
              <h3 className="text-base font-semibold text-white flex items-center gap-2">
                <TrendingUp size={16} className="text-emerald-400" />
                7-Day Security Score Forecast
              </h3>
              <p className="text-xs text-slate-500 mt-0.5">
                Predicted score with confidence interval
              </p>
            </div>
          </div>

          <ResponsiveContainer width="100%" height={250}>
            <AreaChart data={forecast}>
              <defs>
                <linearGradient id="confArea" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor="#10b981" stopOpacity={0.3} />
                  <stop offset="100%" stopColor="#10b981" stopOpacity={0} />
                </linearGradient>
              </defs>
              <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
              <XAxis dataKey="day" tick={{ fill: "#64748b", fontSize: 11 }} />
              <YAxis
                domain={[0, 100]}
                tick={{ fill: "#64748b", fontSize: 11 }}
              />
              <Tooltip
                contentStyle={{
                  backgroundColor: "#0d1117",
                  border: "1px solid #1e293b",
                  borderRadius: 8,
                }}
              />
              <Legend wrapperStyle={{ fontSize: 11 }} />
              <Area
                type="monotone"
                dataKey="upper"
                stroke="transparent"
                fill="url(#confArea)"
                name="Upper bound"
              />
              <Area
                type="monotone"
                dataKey="lower"
                stroke="transparent"
                fill="#0d1117"
                name="Lower bound"
              />
              <Line
                type="monotone"
                dataKey="expected"
                stroke="#10b981"
                strokeWidth={2.5}
                dot={{ fill: "#10b981", r: 4 }}
                name="Predicted score"
              />
            </AreaChart>
          </ResponsiveContainer>
        </div>
      )}

      <div className="max-w-6xl mx-auto grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Trend chart */}
        {trend && trend.length > 0 && (
          <div className="bg-[#111827] border border-slate-800 rounded-2xl p-6">
            <h3 className="text-base font-semibold text-white mb-1">
              Security Score Trend
            </h3>
            <p className="text-xs text-slate-500 mb-5">Last 4 weeks</p>

            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={trend}>
                <CartesianGrid strokeDasharray="3 3" stroke="#1e293b" />
                <XAxis dataKey="day" tick={{ fill: "#64748b", fontSize: 11 }} />
                <YAxis
                  domain={[0, 100]}
                  tick={{ fill: "#64748b", fontSize: 11 }}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: "#0d1117",
                    border: "1px solid #1e293b",
                    borderRadius: 8,
                  }}
                />
                <Line
                  type="monotone"
                  dataKey="score"
                  stroke="#f59e0b"
                  strokeWidth={2.5}
                  dot={{ fill: "#f59e0b", r: 4 }}
                  name="Security score"
                />
              </LineChart>
            </ResponsiveContainer>
          </div>
        )}

        {/* At-risk pages */}
        <div className="bg-[#111827] border border-slate-800 rounded-2xl p-6">
          <h3 className="text-base font-semibold text-white mb-1 flex items-center gap-2">
            <AlertTriangle size={15} className="text-amber-400" />
            High-Risk Pages
          </h3>
          <p className="text-xs text-slate-500 mb-5">
            Pages with Critical or High severity findings
          </p>

          {!at_risk || at_risk.length === 0 ? (
            <div className="py-8 text-center text-slate-500 text-sm">
              No high-risk pages detected.
            </div>
          ) : (
            <div className="space-y-3">
              {at_risk.map((page, i) => (
                <div
                  key={i}
                  className="bg-slate-900/40 border border-slate-800 rounded-xl p-3"
                >
                  <div className="flex items-start justify-between gap-3 mb-1.5">
                    <div className="flex items-center gap-2 min-w-0 flex-1">
                      <Globe size={11} className="text-slate-500 shrink-0" />
                      <span className="text-xs font-mono text-slate-300 truncate">
                        {page.url}
                      </span>
                    </div>
                    <span
                      className={`text-xs font-bold shrink-0 ${
                        page.risk >= 8
                          ? "text-red-400"
                          : page.risk >= 6
                            ? "text-orange-400"
                            : "text-amber-400"
                      }`}
                    >
                      {Number(page.risk || 0).toFixed(1)}/10
                    </span>
                  </div>
                  <p className="text-[11px] text-slate-500 ml-4">
                    {page.reason}
                  </p>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
